/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package Linketinder.Gradle

import Linketinder.Gradle.BancoDeDados.Banco

static void main(String[] args) {
    Scanner scan = new Scanner(System.in)
    boolean exit = false
    while(!exit){
        println("Escolha uma opção: " +
                "\n 1 - Listar Empresas " +
                "\n 2 - Listar Candidatos " +
                "\n 3 - Listar Vagas" +
                "\n 4 - Inserir novo Candidato " +
                "\n 5 - Inserir nova Empresa " +
                "\n 6 - Sair"
        )
        int opcao = scan.nextInt();
        switch(opcao){
            case 1:
                Banco.listar_empresas()
                break
            case 2:
                Banco.listar_candidatos()
                break
            case 3:
                Banco.listar_vagas()
                break
            case 4:
                Banco.inserir_candidato()
                break
            case 5:
                Banco.inserir_empresa()
                break
            case 6:
                exit = true
                break
            default :
                println("Escolha uma opção válida")
        }
    }
}
