/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package Linketinder.Gradle

import Linketinder.Gradle.Classes.PessoaFisica
import spock.lang.Specification

class AppTest extends Specification {

}
